FROM golang:1.16.6-alpine3.14

WORKDIR /go/src/app
COPY src/controllers/ ./src/controllers/
COPY go.mod go.sum ./

RUN go install -v ./...
RUN go build -o actions ./src/controllers/

CMD ["./actions"]
